version: '3.9'
services:
  web:
    container_name: nginx
    image: nginx
    volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
    - "80:80"
  db:
    container_name: pgsql
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: home-app-center
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: haohl@local.cn
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - /var/lib/pgadmin:/var/lib/pgadmin
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - USER=haohl 
      - PASS=benimaru97;
    volumes:
      - ~/transmission/config:/config
      - ~/transmission/downloads:/downloads
      - ~/transmission/watch:/watch
    ports:
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped