version: '3.9'
services:
  web:
    container_name: nginx
    image: nginx
    restart: unless-stopped
    volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d
    - ./portal/dist:/usr/share/nginx/html
    ports:
    - "80:80"
  db:
    container_name: pgsql
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - /var/lib/pgadmin:/var/lib/pgadmin
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - "USER=${TRANSIMSSION_USER}" 
      - "PASS=${TRANSIMSSION_PASSWORD}"
    volumes:
      - ~/transmission/config:/config
      - ~/transmission/downloads:/downloads
      - ~/transmission/watch:/watch
    ports:
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped